title: Home
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog covering topics including cyber security education, open source intelligence
  techniques, and others within the realm of computer science.
show_excerpts: true
baseurl: ""
url: "https://ebristow.com"
include: [CNAME]

permalink: /blog/:title

# holy moly I spent 1.5 hours trying to get the site to work and it was this line
# for the love of all things good don't uncommenttttt
#theme: texture

remote_theme: samarsault/texture

texture:
  title: Erin Bristow
  tagline: Computer Science Student.
  style: black

  social_links:
    github: erin-bristow
    linkedIn: in/erinbristow

  showNav: true
  navigation:
    - title: Home
      url: "/"
  disqus_shortname: ebristow-com
  

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-target-blank
